export const APP_LOADED = 'APP_LOADED';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const ADD_SQUABBLE = 'ADD_SQUABBLE';
export const SQUABBLELIST_LOADED = 'SQUABBLELIST_LOADED';
export const SQUABBLE_CHALLENGE = 'SQUABBLE_CHALLENGE';

export const ARGUMENTLIST_LOADED = 'ARGUMENTLIST_LOADED';
export const ANTI_ARGUMENTLIST_LOADED = 'ANTI_ARGUMENTLIST_LOADED';

export const ARGUMENT_SUBMIT = 'ARGUMENT_SUBMIT';
export const ANTI_ARGUMENT_SUBMIT = 'ANTI_ARGUMENT_SUBMIT';
export const ARGUMENT_SELECT = 'ARGUMENT_SELECT';

export const SQUABBLE_LOADED = 'SQUABBLE_LOADED';
export const SQUABBLE_SELECT = 'SQUABBLE_SELECT';

export const COMMENTLIST_LOADED = 'COMMENTLIST_LOADED';

export const COMMENTCHILDLIST_LOAD = 'COMMENTCHILDLIST_LOAD';
export const COMMENTCHILDLIST_UNLOAD = 'COMMENTCHILDLIST_UNLOAD';

export const COMMENT_SUBMIT = 'COMMENT_SUBMIT';


